service: green-screen-remover

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 3008
  timeout: 900
  environment:
    OUTPUT_BUCKET: your-video-engine-uploads
    JOBS_TABLE: green-screen-jobs
    JOB_QUEUE_URL:
      Ref: JobQueue
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/green-screen-jobs
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::your-video-engine-uploads/*
    - Effect: Allow
      Action:
        - sqs:*
      Resource: "*"
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: "*"

functions:
  submit:
    handler: src/submit.handler
    timeout: 29
    events:
      - http:
          path: submit
          method: post
    environment:
      JOBS_TABLE: ${self:provider.environment.JOBS_TABLE}
      JOB_QUEUE_URL: { Ref: JobQueue }

  status:
    handler: src/status.handler
    timeout: 29
    events:
      - http:
          path: status/{jobId}
          method: get
    environment:
      JOBS_TABLE: ${self:provider.environment.JOBS_TABLE}

  worker:
    handler: src/worker.handler
    timeout: 900
    layers:
      - arn:aws:lambda:us-east-1:339712823540:layer:ffmpeg:1
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JobQueue
              - Arn
    environment:
      OUTPUT_BUCKET: ${self:provider.environment.OUTPUT_BUCKET}
      JOBS_TABLE: ${self:provider.environment.JOBS_TABLE}

resources:
  Resources:
    JobQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: GreenScreenJobQueue
        VisibilityTimeout: 65

    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: green-screen-jobs
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: jobId
            AttributeType: S
        KeySchema:
          - AttributeName: jobId
            KeyType: HASH
