service: queues

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  timeout: 30
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    QUEUES_TABLE: QueuesTable-${sls:stage}
    HEYGEN_RENDER_URL: https://api.heygen.com/v2/video/generate
    HEYGEN_STATUS_URL: https://api.heygen.com/v1/video_status.get
    HEYGEN_API_KEY: NTA1ZDliMjc3OTE5NDFmYmIxMGIzZWI3ZTVkZDg4MjAtMTcxOTU5NzI0Nw==
    REMOTION_RENDER_URL: ${self:custom.remotionRenderUrl.${sls:stage}}
    REMOTION_STATUS_URL: ${self:custom.remotionStatusUrl.${sls:stage}}
    DEEPGRAM_URL: https://api.deepgram.com/v1/listen
    DEEPGRAM_API_KEY: 41c7a04040a50fa21f6267d0647dc0603ace9325
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/QueuesTable-${sls:stage}
            - arn:aws:dynamodb:${self:provider.region}:*:table/QueuesTable-${sls:stage}/index/QueueTypeStatusIndex
        - Effect: Allow
          Action:
            - events:PutRule
            - events:PutTargets
            - events:RemoveTargets
            - events:DeleteRule
            - events:DescribeRule
            - events:ListRules
            - events:ListTargetsByRule
          Resource: "*"
  apiGateway:
    apiKeys:
      - queue-${sls:stage}-key

package:
  individually: true

functions:
  enqueueHandler:
    handler: index.enqueueHandler
    events:
      - http:
          path: enqueue
          method: post
          cors: true
          private: true
  worker:
    handler: index.workerHttpHandler
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild

custom:
  remotionRenderUrl:
    dev: "https://ezh73b8y6l.execute-api.us-east-1.amazonaws.com/dev/render"
    prod: "https://0lxwxeqkpl.execute-api.us-east-1.amazonaws.com/prod/render"
  remotionStatusUrl:
    dev: "https://ezh73b8y6l.execute-api.us-east-1.amazonaws.com/dev/status"
    prod: "https://0lxwxeqkpl.execute-api.us-east-1.amazonaws.com/prod/status"
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node18
    platform: node
    concurrency: 10

resources:
  Resources:
    QueuesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: QueuesTable-${sls:stage}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: queueType
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: QueueTypeStatusIndex
            KeySchema:
              - AttributeName: queueType
                KeyType: HASH
              - AttributeName: status
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
